import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import {
  faFaceSmile,
  faFaceSadTear,
  faCircleCheck,
} from "@fortawesome/free-regular-svg-icons";

import {
  faShopify,
  faFacebook,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";

import {
  faEye,
  faPen,
  faLock,
  faGear,
  faBars,
  faStar,
  faPlus,
  faBell,
  faUser,
  faUsers,
  faCheck,
  faXmark,
  faShirt,
  faMinus,
  faFilter,
  faCircle,
  faLockOpen,
  faEyeSlash,
  faArrowLeft,
  faUserGroup,
  faCaretDown,
  faListCheck,
  faArrowUpAZ,
  faArrowUpZA,
  faBoxArchive,
  faChartSimple,
  faCircleXmark,
  faPenToSquare,
  faAddressCard,
  faArrowDownAZ,
  faArrowDownZA,
  faHandsBubbles,
  IconDefinition,
  faRightFromBracket,
  faCircleChevronLeft,
  faCircleChevronRight,
  faArrowUpRightFromSquare,
} from "@fortawesome/free-solid-svg-icons";

const wrapIcon = (icon: IconDefinition) => {
  return <FontAwesomeIcon icon={icon} />;
};

const icons = {
  eye: wrapIcon(faEye),
  pen: wrapIcon(faPen),
  gear: wrapIcon(faGear),
  lock: wrapIcon(faLock),
  user: wrapIcon(faUser),
  bell: wrapIcon(faBell),
  plus: wrapIcon(faPlus),
  minus: wrapIcon(faMinus),
  cross: wrapIcon(faXmark),
  shirt: wrapIcon(faShirt),
  check: wrapIcon(faCheck),
  users: wrapIcon(faUsers),
  menuBars: wrapIcon(faBars),
  filter: wrapIcon(faFilter),
  solidStar: wrapIcon(faStar),
  shopify: wrapIcon(faShopify),
  facebook: wrapIcon(faFacebook),
  eyeClosed: wrapIcon(faEyeSlash),
  solidCircle: wrapIcon(faCircle),
  archive: wrapIcon(faBoxArchive),
  faceSmile: wrapIcon(faFaceSmile),
  arrowLeft: wrapIcon(faArrowLeft),
  lockOpened: wrapIcon(faLockOpen),
  listCheck: wrapIcon(faListCheck),
  arrowUpAZ: wrapIcon(faArrowUpAZ),
  arrowUpZA: wrapIcon(faArrowUpZA),
  instagram: wrapIcon(faInstagram),
  caretDown: wrapIcon(faCaretDown),
  userGroup: wrapIcon(faUserGroup),
  faceTear: wrapIcon(faFaceSadTear),
  barChart: wrapIcon(faChartSimple),
  squaredPen: wrapIcon(faPenToSquare),
  circleXmark: wrapIcon(faCircleXmark),
  circleCheck: wrapIcon(faCircleCheck),
  arrowDownAZ: wrapIcon(faArrowDownAZ),
  addressCard: wrapIcon(faAddressCard),
  arrowDownZA: wrapIcon(faArrowDownZA),
  handsWaving: wrapIcon(faHandsBubbles),
  entering: wrapIcon(faRightFromBracket),
  chevronLeft: wrapIcon(faCircleChevronLeft),
  chevronRight: wrapIcon(faCircleChevronRight),
  solidLinkDirect: wrapIcon(faArrowUpRightFromSquare),
};

export default icons;
